version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: yobasystems/alpine-mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /srv/dev-disk-by-label-datadisk/data/appdata/Nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=721128
      - MYSQL_PASSWORD=721128
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    ports:
      - 8090:80
    links:
      - db
    volumes:
      - /srv/dev-disk-by-label-archive/archive/Nextcloud:/var/www/html
    restart: always 
